export const PRODUCTS = [{
  id: 1,
  title: "Sony WH-1000XM3...",
  image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcS9VW3GZVi-Lv8uBGCgViTyeNAMlWWHJ8A1RuridO_VHGbcAFz2zBjuXoLClRowKNnZXCJWxopzyzg5hOrAgwuoUXO8sbE9inrkThXZHr0rPCICbV-b44hY&usqp=CAE",
  price: 773,
  description: "Industry leading Active Noise...",
  brand: "sony",
  model: "WH-1000XM3",
  color: "silver",
  category: "audio",
  discount: 11
},
{
  id: 2,
  title: "Microsoft Xbox...",
  image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQvcHbkYa0pmufLkIAtUZkOCGNhMr5Gy4OZRe_Q3PqGfhzelwzYNBvQho4d-EPu2rFUGx2GG2tBuQAeMaapzKboOsEMEJCag3OhdwvPSAX9H0PRWXpJkwrmMQ&usqp=CAE",
  price: 57,
  description: "Experience the modernized design of the Xbox...",
  brand: "microsoft",
  model: "Xbox X/S",
  color: "white",
  category: "gaming",
  popular: true,
  discount: 4
},
{
  id: 3,
  title: "Sony WH-1000XM3...",
  image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcS9VW3GZVi-Lv8uBGCgViTyeNAMlWWHJ8A1RuridO_VHGbcAFz2zBjuXoLClRowKNnZXCJWxopzyzg5hOrAgwuoUXO8sbE9inrkThXZHr0rPCICbV-b44hY&usqp=CAE",
  price: 773,
  description: "Industry leading Active Noise...",
  brand: "sony",
  model: "WH-1000XM3",
  color: "silver",
  category: "audio",
  discount: 11
},
{
  id: 4,
  title: "Microsoft Xbox...",
  image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQvcHbkYa0pmufLkIAtUZkOCGNhMr5Gy4OZRe_Q3PqGfhzelwzYNBvQho4d-EPu2rFUGx2GG2tBuQAeMaapzKboOsEMEJCag3OhdwvPSAX9H0PRWXpJkwrmMQ&usqp=CAE",
  price: 57,
  description: "Experience the modernized design of the Xbox...",
  brand: "microsoft",
  model: "Xbox X/S",
  color: "white",
  category: "gaming",
  popular: true,
  discount: 4
},
{
  id: 5,
  title: "Sony WH-1000XM3...",
  image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcS9VW3GZVi-Lv8uBGCgViTyeNAMlWWHJ8A1RuridO_VHGbcAFz2zBjuXoLClRowKNnZXCJWxopzyzg5hOrAgwuoUXO8sbE9inrkThXZHr0rPCICbV-b44hY&usqp=CAE",
  price: 773,
  description: "Industry leading Active Noise...",
  brand: "sony",
  model: "WH-1000XM3",
  color: "silver",
  category: "audio",
  discount: 11
},
{
  id: 6,
  title: "Microsoft Xbox...",
  image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQvcHbkYa0pmufLkIAtUZkOCGNhMr5Gy4OZRe_Q3PqGfhzelwzYNBvQho4d-EPu2rFUGx2GG2tBuQAeMaapzKboOsEMEJCag3OhdwvPSAX9H0PRWXpJkwrmMQ&usqp=CAE",
  price: 57,
  description: "Experience the modernized design of the Xbox...",
  brand: "microsoft",
  model: "Xbox X/S",
  color: "white",
  category: "gaming",
  popular: true,
  discount: 4
},{
  id: 7,
  title: "Sony WH-1000XM3...",
  image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcS9VW3GZVi-Lv8uBGCgViTyeNAMlWWHJ8A1RuridO_VHGbcAFz2zBjuXoLClRowKNnZXCJWxopzyzg5hOrAgwuoUXO8sbE9inrkThXZHr0rPCICbV-b44hY&usqp=CAE",
  price: 773,
  description: "Industry leading Active Noise...",
  brand: "sony",
  model: "WH-1000XM3",
  color: "silver",
  category: "audio",
  discount: 11
},
{
  id: 8,
  title: "Microsoft Xbox...",
  image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQvcHbkYa0pmufLkIAtUZkOCGNhMr5Gy4OZRe_Q3PqGfhzelwzYNBvQho4d-EPu2rFUGx2GG2tBuQAeMaapzKboOsEMEJCag3OhdwvPSAX9H0PRWXpJkwrmMQ&usqp=CAE",
  price: 57,
  description: "Experience the modernized design of the Xbox...",
  brand: "microsoft",
  model: "Xbox X/S",
  color: "white",
  category: "gaming",
  popular: true,
  discount: 4
},
{
  id: 9,
  title: "Sony WH-1000XM3...",
  image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcS9VW3GZVi-Lv8uBGCgViTyeNAMlWWHJ8A1RuridO_VHGbcAFz2zBjuXoLClRowKNnZXCJWxopzyzg5hOrAgwuoUXO8sbE9inrkThXZHr0rPCICbV-b44hY&usqp=CAE",
  price: 773,
  description: "Industry leading Active Noise...",
  brand: "sony",
  model: "WH-1000XM3",
  color: "silver",
  category: "audio",
  discount: 11
},
{
  id: 10,
  title: "Microsoft Xbox...",
  image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQvcHbkYa0pmufLkIAtUZkOCGNhMr5Gy4OZRe_Q3PqGfhzelwzYNBvQho4d-EPu2rFUGx2GG2tBuQAeMaapzKboOsEMEJCag3OhdwvPSAX9H0PRWXpJkwrmMQ&usqp=CAE",
  price: 57,
  description: "Experience the modernized design of the Xbox...",
  brand: "microsoft",
  model: "Xbox X/S",
  color: "white",
  category: "gaming",
  popular: true,
  discount: 4
},
{
  id: 11,
  title: "Sony WH-1000XM3...",
  image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcS9VW3GZVi-Lv8uBGCgViTyeNAMlWWHJ8A1RuridO_VHGbcAFz2zBjuXoLClRowKNnZXCJWxopzyzg5hOrAgwuoUXO8sbE9inrkThXZHr0rPCICbV-b44hY&usqp=CAE",
  price: 773,
  description: "Industry leading Active Noise...",
  brand: "sony",
  model: "WH-1000XM3",
  color: "silver",
  category: "audio",
  discount: 11
},
{
  id: 12,
  title: "Microsoft Xbox...",
  image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQvcHbkYa0pmufLkIAtUZkOCGNhMr5Gy4OZRe_Q3PqGfhzelwzYNBvQho4d-EPu2rFUGx2GG2tBuQAeMaapzKboOsEMEJCag3OhdwvPSAX9H0PRWXpJkwrmMQ&usqp=CAE",
  price: 57,
  description: "Experience the modernized design of the Xbox...",
  brand: "microsoft",
  model: "Xbox X/S",
  color: "white",
  category: "gaming",
  popular: true,
  discount: 4
},
{
  id: 13,
  title: "Sony WH-1000XM3...",
  image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcS9VW3GZVi-Lv8uBGCgViTyeNAMlWWHJ8A1RuridO_VHGbcAFz2zBjuXoLClRowKNnZXCJWxopzyzg5hOrAgwuoUXO8sbE9inrkThXZHr0rPCICbV-b44hY&usqp=CAE",
  price: 773,
  description: "Industry leading Active Noise...",
  brand: "sony",
  model: "WH-1000XM3",
  color: "silver",
  category: "audio",
  discount: 11
},
{
  id: 14,
  title: "Microsoft Xbox...",
  image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQvcHbkYa0pmufLkIAtUZkOCGNhMr5Gy4OZRe_Q3PqGfhzelwzYNBvQho4d-EPu2rFUGx2GG2tBuQAeMaapzKboOsEMEJCag3OhdwvPSAX9H0PRWXpJkwrmMQ&usqp=CAE",
  price: 57,
  description: "Experience the modernized design of the Xbox...",
  brand: "microsoft",
  model: "Xbox X/S",
  color: "white",
  category: "gaming",
  popular: true,
  discount: 4
}];
